MODEL:
  NAME: 'resnet50'
  BACKBONE_EMB_SIZE: 2048
  PRETRAIN_PATH: '/home/chanhyuk/git/centroids-reid/logs/market1501/train_ctl_model/version_0/auto_checkpoints/checkpoint_162.pth'
  KEEP_CAMID_CENTROIDS: True

INPUT:
  SIZE_TRAIN: [256,128]
  SIZE_TEST: [256,128]

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  BASE_LR: 0.0001
  OPTIMIZER_NAME: "Adam"
  MAX_EPOCHS: 120
  EVAL_PERIOD: 40

USE_MIXED_PRECISION: True

REPRODUCIBLE_NUM_RUNS: 3
OUTPUT_DIR: 'data/market1501/output'
GPU_IDS: [0]

DATASETS:
  ROOT_DIR: 'data/market1501/query'

TEST:
  IMS_PER_BATCH: 128
  ONLY_TEST: True
